### ISSUE TITLE
Cleanup Starter branch and Recreate layouts

### ISSUE THREAD

**Issue by Divyesh-Johri** [Divyesh-Johri/ecc-case-comp-app#8]
Figure out what needs to be done/complete it:
https://github.com/Divyesh-Johri/ecc-case-comp-app/issues/5

**Comment by pdugery** [comment]
[Drive folder with photos of page layouts](https://drive.google.com/drive/u/0/folders/1C3NPpwclsNSGmqYg7ZjnyKMlDYgu_4nC)
